#!/bin/bash
# Helper functions used by several scripts.

export OPENSHIFT_RUNTIME_DIR=${OPENSHIFT_DIY_DIR}/runtime/
export OPENSHIFT_RUN_DIR=${OPENSHIFT_DIY_DIR}/run/
export OPENSHIFT_BIN=${OPENSHIFT_RUNTIME_DIR}/bin/

# Fix PHP Path
export PATH=${OPENSHIFT_BIN}:${OPENSHIFT_RUNTIME_DIR}/php5/bin/:$PATH

# When using rockmongo this is set and can cause strange errors here
export PHPRC=${OPENSHIFT_RUNTIME_DIR}/etc/php5/
